adminUser:
  password: vault:pr-210-7-boot-eks/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-210-7-boot-eks/pipelineUser:token
  username: cjxd-bot-test
prow:
  hmacToken: vault:pr-210-7-boot-eks/prow:hmacToken
